#ifndef ZMQINTERFACE_GLOBAL_H
#define ZMQINTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ZMQINTERFACE_LIBRARY)
#  define ZMQINTERFACESHARED_EXPORT Q_DECL_EXPORT
#else
#  define ZMQINTERFACESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ZMQINTERFACE_GLOBAL_H
